## Analysis for CCS3

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Some basic data loading and cleanup of useless columns

In [ ]:
def clean_df(df: pd.DataFrame):
    df['TOI'] = df['TOI'].replace('ch3 (1)', 'ch3')
    df['TOI'] = df['TOI'].replace('ch5 (1)', 'ch5')
    df['TOI'] = df['TOI'].replace('ch7 (1)', 'ch7')
    df['TOI'] = df['TOI'].replace('ch9 (1)', 'ch9')

    df['TOI'] = df['TOI'].replace('d2 (1)', 'd2')
    df['TOI'] = df['TOI'].replace('d5 (1)', 'd5')
    df['TOI'] = df['TOI'].replace('f2 (1)', 'f2')
    df['TOI'] = df['TOI'].replace('f3 (1)', 'f3')
    df['TOI'] = df['TOI'].replace('f4 (1)', 'f4')

    df['TOI'] = df['TOI'].replace('ts_1', 'ts1')
    df['TOI'] = df['TOI'].replace('ts3 (1)', 'ts3')
    df['TOI'] = df['TOI'].replace('ts4 (1)', 'ts4')
    df['TOI'] = df['TOI'].replace('ts5 (1)', 'ts5')
    df['TOI'] = df['TOI'].replace('ts6 (1)', 'ts6')
    df['TOI'] = df['TOI'].replace('ts7 (1)', 'ts7')
    df['TOI'] = df['TOI'].replace('ts8 (1)', 'ts8')
    df['TOI'] = df['TOI'].replace('ts9 (1)', 'ts9')
    df['TOI'] = df['TOI'].replace('ts10 (1)', 'ts10')
    
    df['Media'] = df['Media'].replace('ch3 (1)', 'ch3')
    df['Media'] = df['Media'].replace('ch5 (1)', 'ch5')
    df['Media'] = df['Media'].replace('ch7 (1)', 'ch7')
    df['Media'] = df['Media'].replace('ch9 (1)', 'ch9')

    df['Media'] = df['Media'].replace('d2 (1)', 'd2')
    df['Media'] = df['Media'].replace('d5 (1)', 'd5')
    df['Media'] = df['Media'].replace('f2 (1)', 'f2')
    df['Media'] = df['Media'].replace('f3 (1)', 'f3')
    df['Media'] = df['Media'].replace('f4 (1)', 'f4')

    df['Media'] = df['Media'].replace('ts_1', 'ts1')
    df['Media'] = df['Media'].replace('ts3 (1)', 'ts3')
    df['Media'] = df['Media'].replace('ts4 (1)', 'ts4')
    df['Media'] = df['Media'].replace('ts5 (1)', 'ts5')
    df['Media'] = df['Media'].replace('ts6 (1)', 'ts6')
    df['Media'] = df['Media'].replace('ts7 (1)', 'ts7')
    df['Media'] = df['Media'].replace('ts8 (1)', 'ts8')
    df['Media'] = df['Media'].replace('ts9 (1)', 'ts9')
    df['Media'] = df['Media'].replace('ts10 (1)', 'ts10')
    
    df['Participant'] = df['Participant'].replace('klara', 'kl')
    df['Participant'] = df['Participant'].replace('Daina', 'da')
    df['Participant'] = df['Participant'].replace('emilia', 'em')
    df['Participant'] = df['Participant'].replace('rea', 're')
    df['Participant'] = df['Participant'].replace('selina', 'sa')
    df['Participant'] = df['Participant'].replace('Frank', 'fr')
    df['Participant'] = df['Participant'].replace('Ananda', 'an')
    df['Participant'] = df['Participant'].replace('Oleg', 'ol')
    df['Participant'] = df['Participant'].replace('jarl_v', 'ja')
    df['Participant'] = df['Participant'].replace('chris', 'ch')
    df['Participant'] = df['Participant'].replace('Alessia', 'al')
    df['Participant'] = df['Participant'].replace('Amalia', 'am')
    df['Participant'] = df['Participant'].replace('yuke', 'yu')
    df['Participant'] = df['Participant'].replace('yesul', 'ye')
    df['Participant'] = df['Participant'].replace('Ida', 'id')
    df['Participant'] = df['Participant'].replace('Sebastian', 'se')
    df['Participant'] = df['Participant'].replace('Anais', 'as')
    df['Participant'] = df['Participant'].replace('dina', 'di')
    df['Participant'] = df['Participant'].replace('Louise', 'lo')
    df['Participant'] = df['Participant'].replace('mathilde', 'ma')
    return df

In [24]:
df = pd.read_csv(f'metrics_cleaned.tsv', sep='\t') 
# cleaned_df = clean_df(df)
# cleaned_df.to_csv('metrics_cleaned.tsv', sep='\t', index=False)

print(df["Participant"].unique())

participants = {name: df[df['Participant']==name] for name in df['Participant'].unique()}

['kl' 'da' 'em' 're' 'sa' 'fr' 'an' 'ol' 'ja' 'ch' 'al' 'am' 'yu' 'ye'
 'id' 'se' 'as' 'di' 'lo' 'ma']

In [6]:
jarl = participants['se']
jarl

,Participant,TOI,Interval,Media,AOI,Duration_of_interval,Start_of_interval,Last_key_press,Total_duration_of_whole_fixations,Average_duration_of_whole_fixations,...,Minimum_duration_of_Visit,Maximum_duration_of_Visit,Number_of_Visits,Time_to_first_Visit,Duration_of_first_Visit,AOI_string,Text_unit_type,First-pass_regression,Regression-path_duration,Re-reading_duration
11272,se,b1,1,b1,.,3217,322591,Space,0,NaN,...,NaN,NaN,0,NaN,NaN,.,Character,NaN,NaN,NaN
11273,se,b1,1,b1,a,3217,322591,Space,0,NaN,...,NaN,NaN,0,NaN,NaN,a,Character,NaN,0.0,0.0
11274,se,b1,1,b1,a,3217,322591,Space,0,NaN,...,NaN,NaN,0,NaN,NaN,a,Character,NaN,0.0,0.0
11275,se,b1,1,b1,a,3217,322591,Space,287,143.0,...,141.0,146.0,2,265.0,141.0,a,Character,1.0,1778.0,1637.0
11276,se,b1,1,b1,b,3217,322591,Space,0,NaN,...,NaN,NaN,0,NaN,NaN,b,Character,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45083,se,ts1,1,ts1,t,4983,49390,Space,0,NaN,...,NaN,NaN,0,NaN,NaN,t,Character,NaN,0.0,0.0
45084,se,ts1,1,ts1,u,4983,49390,Space,0,NaN,...,NaN,NaN,0,NaN,NaN,u,Character,NaN,0.0,0.0
45085,se,ts1,1,ts1,v,4983,49390,Space,0,NaN,...,NaN,NaN,0,NaN,NaN,v,Character,NaN,0.0,0.0
45086,se,ts1,1,ts1,y,4983,49390,Space,0,NaN,...,NaN,NaN,0,NaN,NaN,y,Character,NaN,0.0,0.0
45087,se,ts1,1,ts1,ц,4983,49390,Space,0,NaN,...,NaN,NaN,0,NaN,NaN,ц,Character,NaN,NaN,NaN

In [25]:
jarl.columns

jarl['TOI'].unique()

array(['b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9', 'b10', 'ch1',
       'ch2', 'ch3', 'ch4', 'ch5', 'ch6', 'ch7', 'ch8', 'ch9', 'ch10',
       'd1', 'd2', 'd3', 'd4', 'd5', 'd6', 'd7', 'd8', 'd9', 'd10', 'f1',
       'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'g1', 'g2',
       'g3', 'g4', 'g5', 'g6', 'g7', 'g8', 'g9', 'g10', 'l1', 'l2', 'l3',
       'l4', 'l5', 'l6', 'l7', 'l8', 'l9', 'l10', 'p1', 'p2', 'p3', 'p4',
       'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'qb', 'qch', 'qd', 'qf', 'qg',
       'ql', 'qp', 'qsh', 'qts', 'sh1', 'sh2', 'sh3', 'sh4', 'sh5', 'sh6',
       'sh7', 'sh8', 'sh9', 'sh10', 'ts2', 'ts3', 'ts4', 'ts5', 'ts6',
       'ts7', 'ts8', 'ts9', 'ts10', 'ts1'], dtype=object)

In [ ]:
# get all participants
participants = {name: df[df['Participant']==name] for name in df['Participant'].unique()}

firsts = {'start': [], 'middle':[], 'end': []}
lasts = {'start': [], 'middle':[], 'end': []}

letters = ['b', 'ch', 'd', 'f', 'g', 'l', 'p', 'sh', 'ts']
cyrillic = ['б', 'ч', 'д', 'ф', 'г', 'л', 'п', 'ш', 'ц']

for participant in participants:
    for i in range(len(letters)):
        # get all toi that equal b1 through b10
        jarl_b = participants[participant][participants[participant]['TOI'].str.match(f'{letters[i]}[0-9]')]
        #order by Start_of_interval
        jarl_b = jarl_b.sort_values(by=['Start_of_interval'])
        # get fixation time of aoi б for its first and last occurence in jarl_b
        firsts.append(jarl_b[jarl_b['AOI']==cyrillic[i]].iloc[0]['Average_duration_of_whole_fixations'])
        lasts.append(jarl_b[jarl_b['AOI']==cyrillic[i]].iloc[-1]['Average_duration_of_whole_fixations'])
    
    
# get average of firsts and lasts without nans
firsts = np.array(firsts)
lasts = np.array(lasts)
firsts = firsts[~np.isnan(firsts)]
lasts = lasts[~np.isnan(lasts)]
firsts.mean(), lasts.mean()

## Basic Analysis

### fixation time of letters, grouped by position-group

### fixation time of each cyrillic letter, t test between first time it got fixated vs last time (to see if they learned)

### average fixation time on latin letters vs on cyrillic (to see if they actually put more effort)

### number of visits (nuumber of fixations???) to the cyrillic letters vs ???

## Questions checking: did they learn better the letters on start/end?

Check how many correct answers each participant got

In [26]:
correct_answers = {
    'b': 2,
    'ch': 2,
    'd': 2,
    'f': 1,
    'g': 2,
    'l': 3,
    'p': 3,
    'sh': 1,
    'ts': 1
}

def check_answers(participant_df: pd.DataFrame):
    questions = participant_df[(participant_df['TOI'].str.contains('q')) & (participant_df['AOI'].str.contains('letter'))]
    answers = {}
    answers['broken'] = 0
    for i, row in questions.iterrows():
        letter = row['Media'][1:]
        key_pressed = row['Last_key_press']
        if key_pressed not in ['1','2','3']:
            answers['broken'] += 1
        else:
            answers[letter] = 1 if int(row['Last_key_press']) == correct_answers[letter] else 0
    answers['total'] = sum(answers.values())
    return answers

# calculate for all participants
all_answers = []
for name, participant in participants.items():
    subj_answer = check_answers(participant)
    subj_answer['Participant'] = name
    all_answers.append(subj_answer)
df = pd.DataFrame(all_answers)
df.sort_values(by='total', ascending=False)

    broken  b  ch    d  f  g  l  p  sh  ts  total Participant
15       0  1   1  1.0  1  1  1  1   1   1      9          se
13       0  1   1  1.0  1  1  1  1   1   1      9          ye
12       0  1   1  1.0  1  1  1  1   1   1      9          yu
0        0  1   0  1.0  1  1  1  1   1   1      8          kl
6        1  1   1  NaN  1  1  0  1   1   1      8          an
7        0  1   0  1.0  1  1  0  1   1   1      7          ol
9        0  1   0  1.0  1  1  0  1   1   1      7          ch
10       0  1   0  1.0  1  1  1  0   1   1      7          al
4        0  1   0  0.0  1  1  1  1   1   0      6          sa
19       0  1   1  1.0  1  0  0  0   1   1      6          ma
8        1  1   1  NaN  1  0  0  1   0   0      5          ja
3        0  1   0  1.0  1  1  0  0   1   0      5          re
2        0  1   0  1.0  1  1  0  0   1   0      5          em
18       0  1   0  0.0  1  1  1  0   1   0      5          lo
5        0  1   0  0.0  1  0  1  0   1   0      4          fr
1        0  1   0  1.0  0  1  0  0   1   0      4          da
17       0  1   1  0.0  0  0  0  0   1   1      4          di
14       0  1   0  0.0  0  1  0  0   1   0      3          id
11       0  1   0  1.0  0  0  0  0   0   0      2          am
16       0  1   0  0.0  0  0  0  0   1   0      2          as

### Group by swapped-letter position

In [19]:
start = df[['b', 'sh', 'g']]
end = df[['l', 'ts', 'p']]
middle = df[['d', 'ch', 'f']]

In [20]:
start_agg = start.aggregate(['sum', 'mean', 'std'])
end_agg = end.aggregate(['sum', 'mean', 'std'])
middle_agg = middle.aggregate(['sum', 'mean', 'std'])

arrays = [
    ['start'] * 3 + ['end'] * 3 + ['middle'] * 3,
    ['b', 'sh', 'g', 'l', 'ts', 'p', 'd', 'ch', 'f']
]
index = pd.MultiIndex.from_arrays(arrays, names=('Position', 'Letter'))

# Combine the aggregated data
combined = pd.concat([start_agg.T, end_agg.T, middle_agg.T])
combined.index = index

combined

                  sum      mean       std
Position Letter
start    b       20.0  1.000000  0.000000
         sh      18.0  0.900000  0.307794
         g       14.0  0.700000  0.470162
end      l        8.0  0.400000  0.502625
         ts      10.0  0.500000  0.512989
         p        9.0  0.450000  0.510418
middle   d       12.0  0.666667  0.485071
         ch       7.0  0.350000  0.489360
         f       15.0  0.750000  0.444262

### Group by letter category

In [21]:
normal = df[['b', 'l', 'd']]
double = df[['sh', 'ts', 'ch']]
greek = df[['g', 'p', 'f']]

In [22]:
normal_agg = normal.aggregate(['sum', 'mean', 'std'])
double_agg = double.aggregate(['sum', 'mean', 'std'])
greek_agg = greek.aggregate(['sum', 'mean', 'std'])

arrays = [
    ['normal'] * 3 + ['double'] * 3 + ['greek'] * 3,
    ['b', 'l', 'd', 'sh', 'ts', 'ch', 'g', 'p', 'f']
]
index = pd.MultiIndex.from_arrays(arrays, names=('Type', 'Letter'))

# Combine the aggregated data
combined = pd.concat([normal_agg.T, double_agg.T, greek_agg.T])
combined.index = index

combined

                sum      mean       std
Type   Letter
normal b       20.0  1.000000  0.000000
       l        8.0  0.400000  0.502625
       d       12.0  0.666667  0.485071
double sh      18.0  0.900000  0.307794
       ts      10.0  0.500000  0.512989
       ch       7.0  0.350000  0.489360
greek  g       14.0  0.700000  0.470162
       p        9.0  0.450000  0.510418
       f       15.0  0.750000  0.444262

In [ ]:
_start = np.array(start).flatten()
_end = np.array(end).flatten()
_middle = np.array(middle).flatten()

In [ ]:
from scipy.stats import ttest_ind

# Perform t-tests between start, end, and middle dataframes
t_test_results = {
    'start_vs_end': ttest_ind(_start, _end, nan_policy='omit').pvalue,
    'start_vs_middle': ttest_ind(_start, _middle, nan_policy='omit').pvalue,
    'end_vs_middle': ttest_ind(_end, _middle, nan_policy='omit').pvalue
}

t_test_results